### ISSUE TITLE
Null model ignored in average models

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#35]
If I create two models, and one is a null model (no predictors), and then I choose to average over the models, in the next step it seems to ignore the null model... 

This only seems to happen if there are count variables in only one of the models... does this make sense?

![image](https://github.com/psolymos/moosecounter/assets/14676081/528e80ca-3bd7-4073-a4d0-6f4370fed2d6)
![Screenshot 2024-02-22 at 14-46-16 Moose Counter 0 7-3](https://github.com/psolymos/moosecounter/assets/14676081/d69bdb29-0a55-4cac-b594-cb08a03d0fb8)

**Comment by psolymos** [comment]
This is unexpected. Thanks @steffilazerte for flagging it.

**Comment by psolymos** [comment]
The null model might not get picked because the the AIC weight is too small.

The only issue I found was with the residual plot that could only show one model at a time. When `model_id` is a vector, we need to pick the 'best' model from the list using `mc_models_total()`.

**Comment by psolymos** [comment]
Actually, it turns out that the plot is produced by `mc_plot_predpi()` that handles the averaging. But it takes the model ID conditional on `length(unique(PI$model_select_id))` which can be length 1 even if we average multiple models. The averaging happens according to the weights. If the weight is low & the number of bootstrap runs is small, we end up with a single ID.

```
ModID <- if (length(unique(PI$model_select_id))>1)
        "Avg" else unique(PI$model_select_id)
```
