### ISSUE TITLE
Inconsistent factor levels for AIC table

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#7]
After converting `GMS` to factor, the model AIC table fails because the factor levels are different (I have no idea why they would be, but it looks like the levels in the model object aren't the complete set?!?)

``` r
library(moosecounter)
#> This is moosecounter 0.4-0    2021-08-19

x <- read.csv(system.file("extdata",
                          "UKH2017_MMU_Querried_data_for_Analysis_Final_3.csv",
                          package = "moosecounter"))

## set response in options
switch_response("total")

## define surveyed units and take a subset as needed
## this also sets total cows value
x <- mc_update_total(x)

x$GMS <- as.factor(x$GMS)

## build model list
ML <- list()
ML[["Model 1"]] <- mc_fit_total(x,
                                vars = c("GMS"),
                                dist="P", weighted=FALSE)

mc_models_total(ML, x)
#> Error in model.frame.default(delete.response(object$terms$full), newdata, : factor GMS has new levels 252, 253, 309
```

<sup>Created on 2021-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by psolymos** [comment]
I think the training (surveyed) set has different levels than the unsurveyed (or all) the data.

When selecting the categorical variables it would make sense to check something like this:

`if (any(table(x[[i]], x[["srv"]]) == 0L)) stop()` where `i` is the categorical variable's name.

```R
> table(x$GMS, x$srv)
     
      FALSE TRUE
  252    71    0
  253    70    0
  257    64   13
  309    58    0
  317    51   10
  318    34   39
  401    63   19
  402    41   28
  403    27   26
> any(table(x$GMS, x$srv) == 0L)
[1] TRUE
```

The contingency table will have 0 where the surveyed or unsurveyed part has no value. Such variable should not be used because we can't predict for a level that is not part of the training data (we can impute something but let's not go there because being different implies that such places are not the average).
